/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a application_adaptor application.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef APPLICATION_ADAPTOR_H
#define APPLICATION_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class int8;
class QVariant;
QT_END_NAMESPACE

class AppInterfaceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.example.Examples.AppInterface")
    Q_CLASSINFO("D-Bus Introspection", ""
                                       "  <interface name=\"org.example.Examples.AppInterface\">\n"
                                       "    <method name=\"play\">\n"
                                       "    <arg direction=\"in\" type=\"s\" name=\"song\"/>\n"
                                       "    </method>\n"
                                       "    <method name=\"pause\"/>\n"
                                      "    <method name=\"nextsong\"/>\n"
                                       "    <arg direction=\"in\" type=\"s\" name=\"song\"/>\n"
                                        "   <arg direction=\"in\" type=\"i\" name=\"currentIndex\"/>\n"
                                       "    </method>\n"
                                       "    <method name=\"prevsong\"/>\n"
                                       "    <arg direction=\"in\" type=\"s\" name=\"song\"/>\n"
                                       "   <arg direction=\"in\" type=\"i\" name=\"currentIndex\"/>\n"
                                       "    </method>\n"
                                       "    <method name=\"stop\"/>\n"
                                       "  </interface>\n"
                                       "")
public:
    AppInterfaceAdaptor(QObject *parent);
    virtual ~AppInterfaceAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void play(QString song);
    void pause();
    void nextsong(QString song);
    void prevsong(QString song);
    void stop();

};

#endif
